# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
