# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='slack_api_key',
            new_name='slack_bot_api_key',
        ),
        migrations.AddField(
            model_name='organization',
            name='glassfrog_anchor_circle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='roles',
            field=models.ManyToManyField(blank=True, to='role.Role'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
