# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20160907_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='glassfrog_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slack_bot_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
