# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='round',
            name='participants_receivers',
            field=models.ManyToManyField(related_name='_round_participants_receivers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='round',
            name='participants_senders',
            field=models.ManyToManyField(related_name='_round_participants_senders_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
