# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_rating_image'),
        ('round', '0004_auto_20170202_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='available_ratings',
            field=models.ManyToManyField(to='feedback.Rating'),
        ),
    ]
