# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-07 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20160907_1421'),
        ('round', '0005_round_available_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
    ]
