# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0005_auto_20160906_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(to='role.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
