# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0002_auto_20160901_1158'),
        ('role', '0002_auto_20160831_1705'),
        ('feedback', '0006_auto_20160902_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='round.Round'),
        ),
        migrations.AddField(
            model_name='feedbackonrole',
            name='remark',
            field=models.ManyToManyField(blank=True, to='feedback.Remark'),
        ),
        migrations.AddField(
            model_name='feedbackonrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.Role'),
        ),
    ]
