# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-18 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_auto_20170411_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='skipped_feedback_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
