# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_feedback_skipped_feedback_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackonrole',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
