# Generated by Django 2.0.6 on 2018-06-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_feedbackonrole_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='actionable_got_reminded',
            field=models.BooleanField(default=False),
        ),
    ]
