# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20160831_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
