# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160831_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_user_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
