# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_slack_user_name'),
        ('user', '0004_auto_rename_email_field'),
    ]

    operations = [
    ]
