# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_auto_20160905_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Circle',
        ),
        migrations.AddField(
            model_name='role',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
