# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0006_auto_20160908_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='accountabilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='role',
            name='domains',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='role',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
    ]
