# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('roles_to_review', models.PositiveSmallIntegerField()),
                ('individuals_to_review', models.PositiveSmallIntegerField()),
                ('min_feedback_sent', models.PositiveIntegerField()),
                ('participants_receivers', models.ManyToManyField(related_name='receivers', to=settings.AUTH_USER_MODEL)),
                ('participants_senders', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
