# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20160906_1134'),
        ('round', '0002_auto_20160901_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='question_for_individual_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.Question'),
        ),
    ]
