# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_round_question_for_individual_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='end_date',
            field=models.DateTimeField(help_text='Editing of feedback will be disabled after this date has passed.'),
        ),
    ]
